In [1]:
import os
import random

import cv2
import numpy as np

import torch
from torch.utils.data import DataLoader
from torchvision import models

from resnet_yolo import resnet50
from yolo_loss import YoloLoss
from dataset import VocDetectorDataset
from eval_voc import evaluate
from predict import predict_image
from config import VOC_CLASSES, COLORS

import matplotlib.pyplot as plt

%matplotlib inline
%load_ext autoreload
%autoreload 2

## Initialization

In [2]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [3]:
# YOLO network hyperparameters
B = 2  # number of bounding box predictions per cell
S = 14  # width/height of network output grid (larger than 7x7 from paper since we use a different network)

To implement Yolo we will rely on a pretrained classifier as the backbone for our detection network. PyTorch offers a variety of models which are pretrained on ImageNet in the [`torchvision.models`](https://pytorch.org/docs/stable/torchvision/models.html) package. In particular, we will use the ResNet50 architecture as a base for our detector. This is different from the base architecture in the Yolo paper and also results in a different output grid size (14x14 instead of 7x7).

Models are typically pretrained on ImageNet since the dataset is very large (> 1million images) and widely used. The pretrained model provides a very useful weight initialization for our detector, so that the network is able to learn quickly and effictively.

In [4]:
load_network_path = None
pretrained = True

# use to load a previously trained network
if load_network_path is not None:
    print('Loading saved network from {}'.format(load_network_path))
    net = resnet50().to(device)
    net.load_state_dict(torch.load(load_network_path))
else:
    print('Load pre-trained model')
    net = resnet50(pretrained=pretrained).to(device)

Load pre-trained model


In [5]:
learning_rate = 0.001
num_epochs = 50
batch_size = 10

# Yolo loss component coefficients (as given in Yolo v1 paper)
lambda_coord = 5
lambda_noobj = 0.5

In [6]:
criterion = YoloLoss(S, B, lambda_coord, lambda_noobj)
optimizer = torch.optim.SGD(net.parameters(), lr=learning_rate, momentum=0.9, weight_decay=5e-4)

## Reading Pascal Data

Since Pascal is a small dataset (5000 in train+val) we have combined the train and val splits to train our detector. This is not typically a good practice, but we will make an exception in this case to be able to get reasonable detection results with a comparatively small object detection dataset.

The train dataset loader also using a variety of data augmentation techniques including random shift, scaling, crop, and flips. Data augmentation is slightly more complicated for detection dataset since the bounding box annotations must be kept consistent through the transformations.

Since the output of the dector network we train is an SxSx(B*5+C), we use an encoder to convert the original bounding box coordinates into relative grid bounding box coordinates corresponding to the the expected output. We also use a decoder which allows us to convert the opposite direction into image coordinate bounding boxes.

In [7]:
file_root_train = 'VOCdevkit_2007/VOC2007/JPEGImages/'
annotation_file_train = 'voc2007.txt'

train_dataset = VocDetectorDataset(root_img_dir=file_root_train,dataset_file=annotation_file_train,train=True, S=S)
train_loader = DataLoader(train_dataset,batch_size=batch_size,shuffle=True,num_workers=4)
print('Loaded %d train images' % len(train_dataset))

Initializing dataset
Loaded 5011 train images


In [ ]:
file_root_test = 'VOCdevkit_2007/VOC2007test/JPEGImages/'
annotation_file_test = 'voc2007test.txt'

test_dataset = VocDetectorDataset(root_img_dir=file_root_test,dataset_file=annotation_file_test,train=False, S=S)
test_loader = DataLoader(test_dataset,batch_size=batch_size,shuffle=False,num_workers=4)
print('Loaded %d test images' % len(test_dataset))

Initializing dataset
Loaded 4950 test images


## Train detector

In [ ]:
best_test_loss = np.inf

for epoch in range(num_epochs):
    net.train()
    
    # Update learning rate late in training
    if epoch == 30 or epoch == 40:
        learning_rate /= 10.0

    for param_group in optimizer.param_groups:
        param_group['lr'] = learning_rate
    
    print('\n\nStarting epoch %d / %d' % (epoch + 1, num_epochs))
    print('Learning Rate for this epoch: {}'.format(learning_rate))
    
    total_loss = 0.
    
    for i, (images, target) in enumerate(train_loader):
        images, target = images.to(device), target.to(device)
        temp = target.cpu().numpy()
        """
        print("classes", np.max(temp) - np.min(temp))
        print(temp.shape)
        print(np.sum(temp[0,:,:,:10], axis=2))
        print(np.sum(temp[0,:,:,10:], axis=2))
        print(target[0].data.shape)
        print(torch.max(target[0], 2))
        """
        pred = net(images)
        loss = criterion(pred,target)
        total_loss += loss.item()
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if (i+1) % 5 == 0:
            print('Epoch [%d/%d], Iter [%d/%d] Loss: %.4f, average_loss: %.4f'
                  % (epoch+1, num_epochs, i+1, len(train_loader), loss.item(), total_loss / (i+1)))
    
    # evaluate the network on the test data
    with torch.no_grad():
        test_loss = 0.0
        net.eval()
        for i, (images, target) in enumerate(test_loader):
            images, target = images.to(device), target.to(device)

            pred = net(images)
            loss = criterion(pred,target)
            test_loss += loss.item()
        test_loss /= len(test_loader)
    
    if best_test_loss > test_loss:
        best_test_loss = test_loss
        print('Updating best test loss: %.5f' % best_test_loss)
        torch.save(net.state_dict(),'best_detector.pth')

    torch.save(net.state_dict(),'detector.pth')
    




Starting epoch 1 / 50
Learning Rate for this epoch: 0.001
[130.32976  399.8045    53.38546    6.983316]
[116.84744  397.64694   55.863056   5.432756]
[104.16557   390.8115     41.25812     4.1775203]
[117.62138   371.07217    57.86422     5.5735893]
[153.4714   354.92096   75.37401    8.778036]
Epoch [1/50], Iter [5/502] Loss: 59.2544, average_loss: 57.0276
[105.092476 331.49854   35.727917   5.930462]
[128.78607   304.85712    57.0192      6.3410287]
[ 80.45647   283.14722    30.569878    4.3683343]
[131.66133  256.62082   64.34158    6.655981]
[ 78.954895  224.1379     38.423485    3.9347196]
Epoch [1/50], Iter [10/502] Loss: 34.5451, average_loss: 50.2991
[ 68.55029   197.9098     36.515728    3.1990955]
[ 96.26031   175.35289    40.835056    4.3319163]
[ 45.814785  152.20897    28.291645    2.6232255]
[ 64.629005 132.72334   30.256529   4.550273]
[ 98.53529  120.949295  43.737946   4.253804]
Epoch [1/50], Iter [15/502] Loss: 26.7476, average_loss: 42.5429
[ 97.12025  105.312965  

Epoch [1/50], Iter [140/502] Loss: 5.8635, average_loss: 13.5511
[44.337013   3.6513588 31.83587    7.412561 ]
[38.393463   3.6397355 32.426765   4.471245 ]
[49.743713   3.6039064 37.39313    5.3660197]
[32.965538   3.6015487 24.319304   4.56653  ]
[54.507267   3.5586138 39.70413    5.7929134]
Epoch [1/50], Iter [145/502] Loss: 10.3563, average_loss: 13.3813
[30.089823   3.5680833 23.565063   3.8616295]
[40.935856   3.527861  30.6499     6.2028785]
[31.082539   3.5128403 23.35329    6.1994123]
[41.62277    3.4852793 35.429768   6.142234 ]
[30.328262   3.4749699 28.233131   4.995074 ]
Epoch [1/50], Iter [150/502] Loss: 6.7031, average_loss: 13.1754
[37.50492    3.4576204 24.961002   6.535663 ]
[33.837547   3.4444911 17.4099     5.0495424]
[35.672688  3.42737  27.53334   4.75581 ]
[55.255547   3.3844733 41.517403   5.752062 ]
[54.799343   3.360301  40.743515   7.6506715]
Epoch [1/50], Iter [155/502] Loss: 10.6554, average_loss: 13.0188
[13.796848   3.3867245 14.669651   2.6064932]
[33.43

# View example predictions

In [ ]:
net.eval()

# select random image from test set
image_name = random.choice(test_dataset.fnames)
image = cv2.imread(os.path.join(file_root_test, image_name))
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

print('predicting...')
result = predict_image(net, image_name, root_img_directory=file_root_test)
for left_up, right_bottom, class_name, _, prob in result:
    color = COLORS[VOC_CLASSES.index(class_name)]
    cv2.rectangle(image, left_up, right_bottom, color, 2)
    label = class_name + str(round(prob, 2))
    text_size, baseline = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.4, 1)
    p1 = (left_up[0], left_up[1] - text_size[1])
    cv2.rectangle(image, (p1[0] - 2 // 2, p1[1] - 2 - baseline), (p1[0] + text_size[0], p1[1] + text_size[1]),
                  color, -1)
    cv2.putText(image, label, (p1[0], p1[1] + baseline), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (255, 255, 255), 1, 8)

plt.figure(figsize = (15,15))
plt.imshow(image)


## Evaluate on Test

To evaluate detection results we use mAP (mean of average precision over each class)

In [ ]:
evaluate(net, test_dataset_file=annotation_file_test)